version: "3.8"

services:
  database:
    hostname: "yourwallet_db"
    container_name: yourwallet_database
    image: postgres:14-alpine

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=your_wallet
  web:
    container_name: your_wallet
    ports:
      - "80:80"
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 80

    depends_on:
      - database